### ISSUE TITLE
Gather A List Of All Routes

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/site_master#11]
Before working on #10, a list of all the viewable routes should be compiled. Searching for `implements ViewableInterface` in the codebase.

**Comment by alexfinnarn** [comment]
Frontpage
- "/" = SiteMaster\Core\Registry\Site\View - The "frontpage" view. Shows a list of scans?

JoinForm: Really just allows you to edit roles you have on a site or edit roles of another user.
- "sites/{site_id}/join/" - Join form for a site.
- "sites/{site_id}/join/{uid}" - Join form for different user than one logged in.

VerifyForm: The same as verifying ownership of a site for Google Webmaster tools. I think this part is a bit much in that the WebAudit project isn't big enough for a central group of people to manage the super admins of each site.
- "sites/{site_id}/verify" - Provides instructions for a user to verify themselves for admin access.

MembersForm: A listing of the current users of a particular site.

**Comment by mfairchild365** [comment]
The "(Analytics)SearchForm" was sort of an experimental feature. We use it from time to time to see how often a framework provided CSS class is used. If it isn't used very much, we can remove it from the framework, or we can target communication about removing it. Otherwise, it tells us that we need to announce the removal to a larger audience.
