### ISSUE TITLE
Evaluate replacing PM2 task runner with Robo

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/site_master#2]
Both projects are actively maintained https://github.com/Unitech/pm2/releases vs. https://github.com/consolidation/Robo/releases.

Both projects are well documented http://pm2.keymetrics.io/docs/usage/cluster-mode/ vs. https://robo.li/getting-started/

While PM2 has it's own monitoring http://pm2.keymetrics.io/docs/usage/monitoring/, it seems like keeping the task runner in PHP would make it easier to monitor along with the overall health of the application.  

We were leaning toward Robo for Digital Asset Management because it seemed to support a lot of common tasks out of the box like https://robo.li/tasks/Assets/.

Since we are committed to Celery for Python apps for another 3-4 years, I'd like to avoid the number of task runners we have to support in production if possible.  If there are technical benefits to PM2, let's identify them.

**Comment by alexfinnarn** [comment]
One reason to keep this in node.js is #6: what the tasks are and how they are run. I know that PHP can gather the source of a page, but you have to connect to an emulator driver in order to load the JS as well. I'm not sure how kicking off scraping of a page via PHP/Robo would work, but Puppeteer can be used instead of Nightmare.js with the same task runner.
